### ISSUE TITLE
error on example

### ISSUE THREAD

**Issue by areski** [nitipit/appkit#20]
I get the following error when trying the example : 
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    from appkit.api.v0_2_6 import App
  File "/home/areski/.virtualenvs/appkit/local/lib/python2.7/site-packages/appkit/api/v0_2_6.py", line 1, in <module>
    from appkit.app import App
  File "/home/areski/.virtualenvs/appkit/local/lib/python2.7/site-packages/appkit/app.py", line 3, in <module>
    from gi.repository import Gtk, Gdk, WebKit
ImportError: No module named gi.repository

I imagine that we should add PyGI as a dependency ?
https://wiki.gnome.org/PyGI

**Comment by nitipit** [comment]
Yeah, I think you're right..
anyway, the package should be 'pygobject' instead ? (PyGI wiki said it has been merged to PyGObject)
https://wiki.gnome.org/PyGObject

**Comment by nitipit** [comment]
Install PyGObject might not that easy.. if you don't use gnome-desktop
For me, I just use the PyGObject which comes with Gnome desktop
but if you've already use Gnome Desktop, when you create the virtual environment with recent virtualenv in python
you need to put `--system-site-packages` option like this

```
$ virtualenv --system-site-packages virtenv
```

To tell python to use PyGObject from system-wide packages

**Comment by nitipit** [comment]
commit: 114435c795d2a0cb2914cf54c9571d22026c2138
you can review that :). I'll just close this issue for now.
thanks for your suggestion

**Comment by areski** [comment]
Thanks for follow up, it works like a charm!
I think it will be important to update your Readme for the new comers like me.
Here a good example : https://github.com/sontek/PyQuil/blob/master/README.markdown

Maybe you can lend it from @sontek
